### ISSUE TITLE
Wi-Fi can't conntect for some users

### ISSUE THREAD

**Issue by Demon000** [Demon000/device_xiaomi_libra#9]
xiaomi_readmac: qmi_nv_read_wlan_mac error
https://github.com/Demon000/device_xiaomi_libra/blob/cm-14.1/modules/readmac/xiaomi_readmac.c#L127

**Comment by ghost** [comment]
Why not set a known (reproducible or generate one with a seed) MAC address for when this error happens, so the user still gets connectivity?

**Comment by Demon000** [comment]
https://github.com/Demon000/device_xiaomi_libra/commit/e0022daa149754636cc5cfa04b82208c5fbf5e99

This should fix it.

**Comment by ghost** [comment]
Latest nightly, 20170816 does not resolve issue.

qmi_nv_api: XIAOMI_QMI_NV: qmi_client_get_service_list() returned 0 num_services = 2
qmi_nv_api: XIAOMI_QMI_NV: qmi_client_get_service_list() returned 0 num_entries = 2 num_services = 2
qmi_nv_api: XIAOMI_QMI_NV: NV Read with nv index 4678 index 0.
qmi_nv_api: XIAOMI_QMI_NV: qmi_client_send_msg_async returned 0
qmi_nv_api: XIAOMI_QMI_NV: Read NV Response: 5, Length: 0
QC-QMI  : qmi_client [4871] 1c: failed to locate client data
xiaomi_readmac: qmi_nv_read_wlan_mac error

Why can't we just set a reproducible MAC address?

**Comment by ghost** [comment]
I'm no longer experiencing this issue. Not sure what changed, but I just flashed your Oreo build, and WiFi connects just fine without issue.

Feel free to close if you've found the cause of the issue, or close since it's no longer effecting me.
